/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blackgalaxy.glb 
Author: Aliaksandr.melas (https://sketchfab.com/alexandr.melas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/inside-galaxy-skybox-hdri-360-panorama-96183eed1ae2425baddb75ca92103f87
Title: Inside Galaxy Skybox HDRI 360 panorama
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function blackgalaxy(props) {
	const { nodes, materials } = useGLTF("/models/blackgalaxy.glb");
	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Object_4.geometry} material={materials.material} rotation={[Math.PI / 2, 0, 0]} />
		</group>
	);
}

useGLTF.preload("/models/blackgalaxy.glb");
